import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL,fileURLToPath} from 'node:url';import {join} from 'node:path';import {mkdtemp,mkdir,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';
import {defineApp,entityStorage,relationalEntityMigration,createBrandModuleRegistry,defineExtensions} from '../runtime/core/index.ts';import {assertEntityStorage} from '../runtime/core/entity-storage.ts';import {localDb,client,boot,alice,root,migrationSql} from './helpers.mjs';import {createApp} from '../bin/lite.mjs';import {scaffoldModuleStorage} from '../bin/module-storage.mjs';
const schema={id:'legacy-proof',name:'Proofs',singular:'Proof',description:'Historical evidence',titleField:'title',fields:[{key:'title',label:'Title',type:'text',required:true},{key:'sourceId',label:'Source',type:'text',required:true}]};
const spec={schema,storage:{kind:'relational',table:'historical_proofs',columns:{sourceId:'source_id'},legacyNullable:['sourceId']}};
async function exercise(db){
 for(const sql of relationalEntityMigration(spec))await db.prepare(sql).run();const app=defineApp({id:'legacy-proof-app',name:'Proof',description:'Proof',modules:[schema]}),options=defineExtensions(app,{registry:createBrandModuleRegistry(app,[{id:schema.id,tables:['historical_proofs'],entitySpecs:{[schema.id]:spec}}])}),call=client(db,alice,undefined,app,options),org=await boot(call),adapter=entityStorage(schema,spec);
 const cols=(await db.prepare('PRAGMA table_info(historical_proofs)').all()).results;assert.equal(cols.find(c=>c.name==='source_id').notnull,0);assert.equal(cols.find(c=>c.name==='title').notnull,1);
 await db.prepare("INSERT INTO historical_proofs(id,org_id,created_by,created_at,updated_at,title,version) VALUES('legacy',?,'original','2020','2020','Historical',7)").bind(org).run();
 const read=()=>call('modules/legacy-proof/records/legacy');const old=(await read()).body.record;assert.equal(old.data.sourceId,null);assert.equal(old.version,7);
 const incomplete=await call('modules/legacy-proof/records',{method:'POST',body:{data:{title:'New without source'}}});assert.equal(incomplete.status,400);assert.equal(incomplete.body.error.code,'required_field');
 assert.throws(()=>adapter.insertStatement({id:'invalid',orgId:org,userId:'alice',now:'2026',data:{title:'Invalid'}}),e=>e.code==='required_field');
 assert.throws(()=>adapter.updateStatement({id:'legacy',orgId:org,version:7,now:'2026',filter:{sql:'1=1',bindings:[]},data:{title:'Invalid replacement'}}),e=>e.code==='required_field');
 assert.throws(()=>adapter.patchStatement({id:'legacy',orgId:org,version:7,now:'2026',filter:{sql:'1=1',bindings:[]},patch:{sourceId:null}}),e=>e.code==='required_field');
 const patch=adapter.patchStatement({id:'legacy',orgId:org,version:7,now:'2026',filter:{sql:'1=1',bindings:[]},patch:{title:'Historical renamed'}});await assert.rejects(()=>db.batch([db.prepare(patch.sql).bind(...patch.bindings),db.prepare('SELECT * FROM no_such_target')]));assert.equal((await read()).body.record.version,7);await db.prepare(patch.sql).bind(...patch.bindings).run();assert.equal((await read()).body.record.data.sourceId,null);assert.equal((await read()).body.record.version,8);
 assert.equal((await call('modules/legacy-proof/records',{method:'POST',body:{data:{title:'New qualified',sourceId:'registered'}}})).status,201);
 assert.equal((await db.prepare("SELECT count(*) n FROM lite_records WHERE module_id='legacy-proof'").first()).n,0);
}
test('legacy nullable storage on SQLite preserves old evidence while new API and server writes remain required',async t=>{const db=await localDb();t.after(()=>db.close());await exercise(db);});
test('legacy nullable storage on D1 preserves old evidence while new API and server writes remain required',async()=>{const wr=createRequire(createRequire(join(root,'template/package.json')).resolve('wrangler/package.json'));const {Miniflare}=await import(pathToFileURL(wr.resolve('miniflare')).href);const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-05-15',d1Databases:['DB'],cf:false});try{const db=await mf.getD1Database('DB');for(const sql of (await migrationSql()).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();await exercise(db);}finally{await mf.dispose();}});
test('legacy nullable mappings are explicit and identical in generated SQL/Drizzle/snapshot; invalid declarations do not change files',async()=>{
 for(const legacyNullable of [['unknown'],['title','title'],['created_at'],'title'])assert.throws(()=>assertEntityStorage({...spec,storage:{...spec.storage,legacyNullable}}));
 const parent=await mkdtemp(join(tmpdir(),'lite-legacy-proof-')),dir=join(parent,'app');try{await createApp({out:dir,spec:fileURLToPath(new URL('../examples/services.json',import.meta.url))});await mkdir(join(dir,'app/modules/'+schema.id),{recursive:true});const result=await scaffoldModuleStorage(dir,schema,spec.storage);assert.deepEqual(result.legacyNullable,['sourceId']);const sql=await readFile(join(dir,result.migration.file),'utf8'),source=await readFile(join(dir,'app/modules/'+schema.id+'/db-schema.ts'),'utf8'),snapshots=(await readdir(join(dir,'drizzle/meta'))).filter(f=>f.endsWith('_snapshot.json')).sort(),snapshot=JSON.parse(await readFile(join(dir,'drizzle/meta',snapshots.at(-1)),'utf8'));assert.ok(sql.includes('"source_id" TEXT)'));assert.ok(source.includes('"source_id":d1Text("source_id")\n'));assert.equal(snapshot.tables.historical_proofs.columns.source_id.notNull,false);const before=await readFile(join(dir,'drizzle/meta/_journal.json'),'utf8');await assert.rejects(scaffoldModuleStorage(dir,{...schema,id:'invalid'},{table:'invalid',columns:spec.storage.columns,legacyNullable:['unknown']}));assert.equal(await readFile(join(dir,'drizzle/meta/_journal.json'),'utf8'),before);}finally{await rm(parent,{recursive:true,force:true});}
});
