import { validateData } from '../core/validation.ts';
import type { Module } from '../core/types';
import type { Api } from './client';
type Tool = {name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown|Promise<unknown>};
export type ModelContext = {registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>};
export function registerLiteTools(context:ModelContext,api:Api,modules:Module[],onMutation:()=>void) {
  const life=new AbortController();
  const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Objet attendu.');return value as Record<string,unknown>;};
  const moduleFor=(id:unknown)=>{const m=modules.find(m=>m.id===id);if(!m)throw new Error('Module inconnu ou inaccessible.');return m;};
  const tools:Tool[]=[
    {name:'creezio_list_modules',title:'Lister les modules',description:'Lire les modules accessibles dans l’espace actuel.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({modules:modules.map(m=>({id:m.id,name:m.name,fields:m.fields}))})},
    {name:'creezio_list_records',title:'Rechercher des documents',description:'Lire jusqu’à 100 documents du module et de l’espace actuels. Utiliser offset pour la pagination.',inputSchema:{type:'object',properties:{moduleId:{type:'string'},query:{type:'string',maxLength:120},offset:{type:'integer',minimum:0,maximum:100000}},required:['moduleId'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{const v=object(input),m=moduleFor(v.moduleId);if(v.query!==undefined&&(typeof v.query!=='string'||v.query.length>120))throw new Error('Recherche invalide.');if(v.offset!==undefined&&(!Number.isInteger(v.offset)||Number(v.offset)<0||Number(v.offset)>100000))throw new Error('Pagination invalide.');return api(`modules/${m.id}/records?limit=100&q=${encodeURIComponent(String(v.query??''))}&offset=${v.offset??0}`);}},
    {name:'creezio_create_record',title:'Créer un document',description:'Enregistrer un nouveau document dans le module et l’espace actuels. Cette action écrit dans la base.',inputSchema:{type:'object',properties:{moduleId:{type:'string'},data:{type:'object'}},required:['moduleId','data'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{const v=object(input),m=moduleFor(v.moduleId),data=validateData(m,v.data);const result=await api(`modules/${m.id}/records`,{method:'POST',body:JSON.stringify({data})});onMutation();return result;}},
    {name:'creezio_update_record',title:'Modifier un document',description:'Remplacer les champs d’un document existant. Fournir tous les champs et la version lue ; un conflit exige une nouvelle lecture.',inputSchema:{type:'object',properties:{moduleId:{type:'string'},recordId:{type:'string'},version:{type:'integer',minimum:1},data:{type:'object'}},required:['moduleId','recordId','version','data'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{const v=object(input),m=moduleFor(v.moduleId);if(typeof v.recordId!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(v.recordId)||!Number.isInteger(v.version)||Number(v.version)<1)throw new Error('Référence ou version invalide.');const data=validateData(m,v.data);const result=await api(`modules/${m.id}/records/${v.recordId}`,{method:'PATCH',body:JSON.stringify({data,version:v.version})});onMutation();return result;}},
  ];
  for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>console.warn(`WebMCP indisponible : ${tool.name}`));}catch{console.warn(`WebMCP indisponible : ${tool.name}`);}
  return ()=>life.abort();
}
