'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { Button,Input,Label,Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@lite/shell-ui/ui/kit';
import { createClient } from './client';
import { State } from './module-view';
import type { Operation } from '../core/operations';
type Group={id:string;name:string;builtin:boolean;locked:boolean;version:number;policyVersion:number;userIds:string[]};
type Catalog={groups:Group[];members:{id:string;name:string;email:string;role:string}[];policies:{group_id:string;operation_id:string;effect:'allow'|'deny'}[];operations:Operation[]};
export function AccessSettings(){
  const api=useMemo(()=>createClient(''),[]),[catalog,setCatalog]=useState<Catalog|null>(null),[selected,setSelected]=useState('role:member'),[query,setQuery]=useState(''),[module,setModule]=useState('all'),[changes,setChanges]=useState<Record<string,'deny'|'inherit'>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [editing,setEditing]=useState<Group|null|undefined>(),[name,setName]=useState(''),[members,setMembers]=useState<string[]>([]);
  const load=useCallback(async()=>{try{setCatalog(await api('access/catalog'));}catch(e){setError((e as Error).message);}},[api]);
  useEffect(()=>{void load();},[load]);
  const group=catalog?.groups.find(g=>g.id===selected),dirty=Object.keys(changes).length>0;
  const editable=(op:Operation)=>!group?.locked&&!op.essential&&(!group?.builtin||op.roles.includes(group.id.slice(5) as any));
  const denied=(id:string)=>changes[id]?changes[id]==='deny':catalog?.policies.some(p=>p.group_id===selected&&p.operation_id===id&&p.effect==='deny');
  const visible=catalog?.operations.filter(op=>(module==='all'||op.moduleId===module)&&(`${op.description} ${op.path} ${op.moduleName}`.toLowerCase().includes(query.toLowerCase())))??[];
  function edit(g:Group|null){setEditing(g);setName(g?.name??'');setMembers(g?.userIds??[]);setError('');}
  function select(id:string){if(dirty&&!window.confirm('Abandonner les changements non enregistrés ?'))return;setSelected(id);setChanges({});setNotice('');}
  async function save(){if(!group)return;setBusy(true);setError('');try{await api(`access/policies/${encodeURIComponent(group.id)}`,{method:'PUT',body:JSON.stringify({version:group.policyVersion,changes:Object.entries(changes).map(([operationId,effect])=>({operationId,effect}))})});setChanges({});await load();setNotice('Droits enregistrés. Ils s’appliquent aux prochains appels API et MCP.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="space-y-4">
    <div className="flex flex-wrap gap-3 items-center"><Label htmlFor="access-group">Groupe</Label><select id="access-group" className="h-10 rounded-md border px-3 text-sm" value={selected} onChange={e=>select(e.target.value)}>{catalog?.groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.userIds.length} membres</option>)}</select><Button variant="outline" onClick={()=>edit(null)}>Créer un groupe</Button>{group&&!group.builtin&&<><Button variant="outline" onClick={()=>edit(group)}>Modifier les membres</Button><Button variant="outline" onClick={()=>{if(!window.confirm(`Supprimer le groupe ${group.name} et ses restrictions ?`))return;void api(`access/groups/${group.id}`,{method:'DELETE'}).then(async()=>{setSelected('role:member');setChanges({});await load();}).catch(e=>setError(e.message));}}>Supprimer le groupe</Button></>}</div>
    <p className="text-sm text-muted-foreground">Les groupes limitent les API accessibles dans le rôle de chaque membre. Si plusieurs groupes s’appliquent, un refus est prioritaire. Les fonctions indispensables restent disponibles et le propriétaire conserve ses accès.</p>
    {group&&<div className="rounded-lg border p-3 text-sm"><strong>{group.name}</strong><p className="mt-1 text-muted-foreground">{catalog?.members.filter(m=>group.userIds.includes(m.id)).map(m=>m.name||m.email).join(', ')||'Aucun membre dans ce groupe.'}</p></div>}
    <div className="flex flex-wrap gap-2"><Input className="max-w-lg" placeholder="Rechercher une API…" aria-label="Rechercher une API" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Module" className="h-10 rounded-md border px-3 text-sm" value={module} onChange={e=>setModule(e.target.value)}><option value="all">Tous les modules</option>{Array.from(new Map(catalog?.operations.map(o=>[o.moduleId,o.moduleName])).entries()).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Button variant="outline" disabled={group?.locked} onClick={()=>setChanges(prev=>({...prev,...Object.fromEntries(visible.filter(editable).map(o=>[o.id,'inherit']))}))}>Autoriser la sélection</Button><Button variant="outline" disabled={group?.locked} onClick={()=>setChanges(prev=>({...prev,...Object.fromEntries(visible.filter(editable).map(o=>[o.id,'deny']))}))}>Refuser la sélection</Button></div><Button disabled={!dirty||busy} onClick={()=>void save()}>{busy?'Enregistrement…':`Enregistrer${dirty?` (${Object.keys(changes).length})`:''}`}</Button></div>
    <State error={error} loading={!catalog}/>{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}
    <div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm text-left"><thead className="border-b bg-muted/50"><tr><th className="p-3">Accès</th><th className="p-3">Module</th><th className="p-3">API</th><th className="p-3">Fonction</th></tr></thead><tbody>{visible.map(op=><tr key={op.id} className="border-b last:border-0"><td className="p-3">{op.essential?<span className="text-muted-foreground">Système requis</span>:group?.locked?<span>Toujours autorisé</span>:!editable(op)?<span className="text-muted-foreground">Exclu par le rôle</span>:<label className="inline-flex gap-2 items-center"><input type="checkbox" aria-label={`Autoriser ${op.description}`} checked={!denied(op.id)} onChange={e=>{setChanges(p=>({...p,[op.id]:e.target.checked?'inherit':'deny'}));setNotice('');}}/>{denied(op.id)?'Refusé':'Autorisé'}</label>}</td><td className="p-3">{op.moduleName}</td><td className="p-3 font-mono text-xs whitespace-nowrap">{op.method} {op.path}</td><td className="p-3">{op.description}</td></tr>)}</tbody></table></div>
    <Dialog open={editing!==undefined} onOpenChange={open=>{if(!open&&!busy)setEditing(undefined);}}><DialogContent><DialogHeader><DialogTitle>{editing?'Modifier le groupe':'Créer un groupe'}</DialogTitle><DialogDescription>Rassemblez les collaborateurs auxquels appliquer les mêmes restrictions.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void(async()=>{let current=editing;if(!current){const created=await api('access/groups',{method:'POST',body:JSON.stringify({name})});current={...created,userIds:[],builtin:false,locked:false,policyVersion:0};}await api(`access/groups/${current!.id}`,{method:'PUT',body:JSON.stringify({name,userIds:members,version:current!.version})});setSelected(current!.id);setChanges({});setEditing(undefined);await load();})().catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><Label htmlFor="group-name">Nom</Label><Input id="group-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><div className="max-h-64 overflow-auto space-y-2">{catalog?.members.map(m=><label key={m.id} className="flex gap-2 text-sm"><input type="checkbox" checked={members.includes(m.id)} onChange={e=>setMembers(p=>e.target.checked?[...p,m.id]:p.filter(id=>id!==m.id))}/>{m.name} · {m.email}</label>)}</div><State error={error}/><Button type="submit" disabled={busy}>{busy?'Enregistrement…':'Enregistrer le groupe'}</Button></form></DialogContent></Dialog>
  </div>;
}
