'use client';
import { useEffect,useMemo,useState } from 'react';
import { Copy,Plus,Trash2 } from 'lucide-react';
import { Button,Card,Input,Label,Select,SelectTrigger,SelectValue,SelectContent,SelectItem,Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@lite/shell-ui/ui/kit';
import { createClient,useLoad } from './client';
import { State } from './module-view';
import { EntityHeader } from './entity-header';
type AccessToken={id:string;name:string;mode:'read'|'write';created_at:string;expires_at:string;revoked_at:string|null};
export function ConnectionsSettings(){
  const api=useMemo(()=>createClient(''),[]),[revision,setRevision]=useState(0),[open,setOpen]=useState(false),[name,setName]=useState(''),[mode,setMode]=useState('read'),[days,setDays]=useState('30'),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
  const {data,error:loadError,loading}=useLoad<{items:AccessToken[]}>(()=>api('access-tokens'),[api,revision]);
  const [endpoint,setEndpoint]=useState('/api/mcp');
  useEffect(()=>setEndpoint(`${window.location.origin}/api/mcp`),[]);
  async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('access-tokens',{method:'POST',body:JSON.stringify({name,mode,days:Number(days)})});setToken(result.token);setRevision(r=>r+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function revoke(id:string){setError('');try{await api(`access-tokens/${id}`,{method:'DELETE'});setRevision(r=>r+1);}catch(e){setError((e as Error).message);}}
  return <section className="workspace-section"><EntityHeader title="API et MCP" description="Connectez vos outils aux données de cet espace. Les modules ajoutés sont disponibles automatiquement." actions={<Button onClick={()=>{setOpen(true);setName('');setToken('');setCopied(false);setError('');}}><Plus size={16}/>Créer une clé</Button>}/>
    <Card className="p-5 space-y-3"><h2 className="font-semibold">Adresse du serveur MCP</h2><Input aria-label="Adresse MCP" value={endpoint} readOnly/><p className="text-sm text-muted-foreground">Transport HTTP avec une clé Bearer. Les outils compatibles peuvent consulter le registre, rechercher et agir sur vos modules selon les droits de la clé. WebMCP utilise directement votre session dans l’application.</p><p className="text-sm">API des données : <code>/api/v1/</code> · Registre des modules : <code>/api/v1/registry</code></p></Card>
    <State error={error||loadError} loading={loading}/>
    <div className="space-y-3">{data?.items.map(item=><Card key={item.id} className="p-4 flex flex-wrap justify-between items-center gap-3"><div><h2 className="font-medium">{item.name}</h2><p className="text-sm text-muted-foreground">{item.mode==='read'?'Lecture seule':'Lecture et écriture'} · {item.revoked_at?'Révoquée':Date.parse(item.expires_at)<Date.now()?'Expirée':`Expire le ${new Date(item.expires_at).toLocaleDateString('fr-FR')}`}</p></div>{!item.revoked_at&&Date.parse(item.expires_at)>Date.now()?<Button variant="outline" onClick={()=>void revoke(item.id)}><Trash2 size={15}/>Révoquer</Button>:null}</Card>)}</div>
    <Dialog open={open} onOpenChange={value=>{if(!busy){setOpen(value);if(!value)setToken('');}}}><DialogContent><DialogHeader><DialogTitle>Créer une clé API</DialogTitle><DialogDescription>Cette clé est personnelle, limitée à cet espace et ne dépasse jamais vos droits actuels. Elle cesse de fonctionner si votre accès est retiré.</DialogDescription></DialogHeader>{token?<div className="space-y-4"><p>Copiez la clé maintenant. Elle ne sera plus affichée ensuite.</p><Input aria-label="Nouvelle clé API" value={token} readOnly onFocus={e=>e.target.select()}/><Button onClick={()=>void navigator.clipboard.writeText(token).then(()=>setCopied(true)).catch(()=>setError('Sélectionnez et copiez la clé dans le champ.'))}><Copy size={15}/>{copied?'Clé copiée':'Copier la clé'}</Button></div>:<form onSubmit={create} className="space-y-4"><div className="field"><Label htmlFor="api-name">Nom de la connexion</Label><Input id="api-name" value={name} onChange={e=>setName(e.target.value)} required maxLength={100} placeholder="Mon outil de travail"/></div><div className="field"><Label>Droits</Label><Select value={mode} onValueChange={setMode}><SelectTrigger aria-label="Droits de la clé"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="read">Lecture seule</SelectItem><SelectItem value="write">Lecture et écriture</SelectItem></SelectContent></Select></div><div className="field"><Label>Validité</Label><Select value={days} onValueChange={setDays}><SelectTrigger aria-label="Validité de la clé"><SelectValue/></SelectTrigger><SelectContent>{['7','30','90'].map(n=><SelectItem key={n} value={n}>{n} jours</SelectItem>)}</SelectContent></Select></div><State error={error}/><Button type="submit" disabled={busy}>{busy?'Création…':'Créer la clé'}</Button></form>}</DialogContent></Dialog>
  </section>;
}
