import {spawnSync} from 'node:child_process';
import {readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const environment=spawnSync(process.execPath,[join(root,'scripts','check-environment.mjs')],{cwd:root,stdio:'inherit'});
if(environment.error)throw environment.error;
if(environment.status!==0)process.exitCode=environment.status??1;
if(process.exitCode)process.exit();
const {syncTemplate}=await import('./sync-template.mjs');
await syncTemplate();
const tests=(await readdir(join(root,'tests'))).filter(p=>p.endsWith('.test.mjs')).sort().map(p=>join(root,'tests',p));
const result=spawnSync(process.execPath,['--test',...tests],{cwd:root,stdio:'inherit'});
if(result.error)throw result.error;process.exitCode=result.status??1;
